export interface Guide {
  slug: string;
  title: string;
  description: string;
  icon: string;
  category: string;
  readTime: string;
  publishedAt: string;
}

export const guides: Guide[] = [
  {
    slug: "nisa-broker-ranking-2026",
    title: "【2026年】新NISAおすすめネット証券ランキングTOP5",
    description: "SBI証券・楽天証券・マネックス証券など主要ネット証券の新NISA対応状況・ポイント還元・取扱銘柄数を徹底比較。初心者におすすめの口座を紹介。",
    icon: "💰",
    category: "nisa",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "roboadvisor-comparison",
    title: "【2026年】ロボアドバイザーおすすめ比較5社",
    description: "ウェルスナビ・THEO・楽ラップ・SUSTEN・ON COMPASSの手数料・運用実績・最低投資額を比較。初心者に最適なロボアドを解説。",
    icon: "🤖",
    category: "roboadvisor",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "ideco-broker-comparison",
    title: "【2026年】iDeCoおすすめ金融機関比較",
    description: "SBI証券・楽天証券・マネックス証券・松井証券のiDeCo手数料・取扱商品数を比較。節税効果を最大化する選び方を解説。",
    icon: "🏦",
    category: "ideco",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "fx-broker-ranking",
    title: "【2026年】FX口座開設キャンペーン比較TOP10",
    description: "GMOクリック・DMM FX・外為どっとコムなど主要FX会社のスプレッド・スワップ・キャンペーン特典を比較。",
    icon: "💹",
    category: "fx-crypto",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "crypto-exchange-comparison",
    title: "【2026年】仮想通貨取引所おすすめ比較",
    description: "bitFlyer・コインチェック・GMOコイン・bitbankの手数料・取扱通貨・セキュリティを比較。初心者におすすめの取引所を紹介。",
    icon: "₿",
    category: "fx-crypto",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "high-reward-credit-cards",
    title: "【2026年】高還元率クレジットカードおすすめ10選",
    description: "還元率1%以上の年会費無料カードから、投資積立で還元を受けられるカードまで。目的別の選び方を解説。",
    icon: "💳",
    category: "card",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "side-business-ranking-2026",
    title: "【2026年】会社員におすすめの副業ランキングTOP10",
    description: "月5万円から狙える副業を厳選。初期費用・必要スキル・想定収入・確定申告の必要性まで徹底解説。",
    icon: "💼",
    category: "sidejob",
    readTime: "15分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "household-budget-apps",
    title: "【2026年】家計簿アプリおすすめ比較",
    description: "マネーフォワードME・Zaim・Money Tree・おかねのコンパスの機能・料金・連携数を比較。無料で使える定番を紹介。",
    icon: "📝",
    category: "household",
    readTime: "8分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "new-nisa-basics",
    title: "新NISA完全ガイド｜始め方・おすすめ銘柄・注意点",
    description: "2024年から始まった新NISAの制度を初心者向けに徹底解説。つみたて投資枠・成長投資枠の使い分けとおすすめ銘柄を紹介。",
    icon: "📖",
    category: "nisa",
    readTime: "15分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "fire-guide",
    title: "【FIRE完全ガイド】40代で経済的自立を達成する方法",
    description: "FIRE（経済的自立と早期退職）達成までの資産目標額、投資戦略、収入増加術を解説。日本人の実例付き。",
    icon: "🔥",
    category: "nisa",
    readTime: "18分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "tax-saving-techniques",
    title: "会社員ができる節税テクニック完全ガイド",
    description: "ふるさと納税・iDeCo・住宅ローン控除・医療費控除など、会社員でも使える節税制度を総まとめ。",
    icon: "💸",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "online-bank-comparison",
    title: "【2026年】ネット銀行金利・手数料比較",
    description: "住信SBIネット銀行・楽天銀行・auじぶん銀行・PayPay銀行の金利・ATM手数料・振込特典を比較。",
    icon: "🏧",
    category: "household",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "sbi-vs-rakuten-nisa",
    title: "SBI証券 vs 楽天証券｜新NISAはどっちがお得？完全比較",
    description: "ネット証券2強のSBI証券と楽天証券を新NISA目線で徹底比較。クレカ積立還元率・ポイント・アプリ使いやすさまで全項目を検証。",
    icon: "⚔️",
    category: "broker",
    readTime: "14分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "furusato-tax-guide-2026",
    title: "【2026年】ふるさと納税完全ガイド｜限度額・おすすめサイト・返礼品",
    description: "ふるさと納税の仕組みから限度額計算、おすすめポータルサイトまで。実質2,000円で返礼品を受け取る方法を解説。",
    icon: "🎁",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "side-business-tax-declaration",
    title: "会社員の副業確定申告ガイド｜20万円ルール・やり方・経費",
    description: "副業収入がある会社員向けに確定申告の必要性・計算方法・経費計上のコツを解説。年間20万円ルールの注意点も。",
    icon: "📋",
    category: "sidejob",
    readTime: "15分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "wealthnavi-vs-theo",
    title: "ウェルスナビ vs THEO｜ロボアド2大サービス徹底比較",
    description: "ロボアドバイザー大手ウェルスナビとTHEOの手数料・運用実績・機能を比較。どちらを選ぶべきかを徹底解説。",
    icon: "🤖",
    category: "roboadvisor",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "crypto-tax-guide",
    title: "仮想通貨の税金完全ガイド｜雑所得の計算方法と節税対策",
    description: "ビットコイン等の仮想通貨で利益が出た場合の税金計算。雑所得の累進課税、損益通算の可否、節税のコツを解説。",
    icon: "💰",
    category: "fx-crypto",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "sbi-securities-review",
    title: "SBI証券の評判・メリット・デメリット｜実際の使用レビュー",
    description: "国内ネット証券口座数No.1のSBI証券を徹底レビュー。手数料・取扱銘柄・アプリの使いやすさまで実体験ベースで解説。",
    icon: "📊",
    category: "broker",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "high-yield-stock-strategy",
    title: "高配当株投資の始め方｜日本株・米国株のおすすめ銘柄",
    description: "配当利回り4%以上の高配当株で不労所得を作る方法。日本高配当株・米国ETFのおすすめと注意点を解説。",
    icon: "💵",
    category: "broker",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "rakuten-securities-review",
    title: "楽天証券の評判・メリット・デメリット｜実際の使用レビュー",
    description: "楽天経済圏ユーザー必見。楽天証券の手数料・ポイント還元・アプリ使いやすさを徹底レビュー。",
    icon: "📊",
    category: "broker",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "monex-securities-review",
    title: "マネックス証券の評判｜クレカ積立1.1%還元の実力",
    description: "マネックスカード積立で業界最高水準1.1%還元のマネックス証券を徹底レビュー。米国株の強みも解説。",
    icon: "📊",
    category: "broker",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "gmo-click-fx-review",
    title: "GMOクリック証券FX徹底レビュー｜国内口座数No.1の理由",
    description: "FX口座開設数国内No.1のGMOクリック証券を徹底解説。スプレッド・スワップ・キャンペーンを検証。",
    icon: "💹",
    category: "fx-crypto",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "dmm-fx-review",
    title: "DMM FX徹底レビュー｜キャッシュバック最大30万円の全条件",
    description: "DMM FXの新規口座開設キャンペーンで最大30万円のキャッシュバックを受ける条件を完全解説。",
    icon: "💹",
    category: "fx-crypto",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "bitflyer-review",
    title: "bitFlyer徹底レビュー｜国内最大手仮想通貨取引所の全貌",
    description: "ビットコイン取引量国内No.1のbitFlyerを徹底解説。手数料・セキュリティ・使いやすさを検証。",
    icon: "₿",
    category: "fx-crypto",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "coincheck-review",
    title: "コインチェック徹底レビュー｜初心者に人気No.1の理由",
    description: "アプリDL数No.1のコインチェックを解説。取扱通貨・手数料・セキュリティを詳しくレビュー。",
    icon: "₿",
    category: "fx-crypto",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "investing-30s-strategy",
    title: "30代から始める投資戦略｜月3万円で将来4,000万円",
    description: "30代会社員向け投資戦略。新NISA・iDeCo・高配当株の組合せで65歳までに4,000万円を作る方法。",
    icon: "📈",
    category: "nisa",
    readTime: "14分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "investing-40s-strategy",
    title: "40代から始める投資戦略｜遅くない！老後資金2,000万円確保",
    description: "40代からでも間に合う投資戦略。限られた時間で効率的に資産形成する方法を年代別に解説。",
    icon: "📈",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "real-estate-crowdfunding",
    title: "不動産クラウドファンディング比較｜1万円から始める不動産投資",
    description: "COZUCHI・CREAL・Funds等の不動産クラウドファンディングを比較。利回り・最低投資額・リスクを解説。",
    icon: "🏠",
    category: "broker",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "insurance-life-comparison",
    title: "生命保険の選び方｜独身・既婚別のおすすめと見直しポイント",
    description: "生命保険の必要性・種類・選び方を解説。ライフステージ別のおすすめ保険金額と保険料の目安を紹介。",
    icon: "🛡️",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "kids-education-fund",
    title: "教育資金準備ガイド｜学資保険 vs NISA、どっちがお得？",
    description: "子どもの教育資金を準備する方法を比較。学資保険と新NISAつみたて投資枠のメリット・デメリット。",
    icon: "🎓",
    category: "household",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "crowdworks-vs-lancers",
    title: "クラウドワークス vs ランサーズ｜会社員の副業おすすめは？",
    description: "国内2大クラウドソーシングを徹底比較。手数料・案件数・稼ぎやすさを会社員副業目線で解説。",
    icon: "💼",
    category: "sidejob",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "blog-side-business",
    title: "ブログ副業で月5万円稼ぐ方法｜WordPress・アフィリエイト入門",
    description: "会社員がブログ副業で月5万円を稼ぐまでのロードマップ。WordPress設定から収益化までを解説。",
    icon: "💻",
    category: "sidejob",
    readTime: "15分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "stock-beginner-guide",
    title: "株式投資の始め方｜初心者が失敗しない7つのルール",
    description: "株式投資初心者が知っておきたい基礎知識と失敗しないためのルール。銘柄選びから売買タイミングまで。",
    icon: "📊",
    category: "broker",
    readTime: "14分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "etf-vs-mutual-fund",
    title: "ETF vs 投資信託｜どっちを選ぶ？メリット・デメリット比較",
    description: "ETF（上場投資信託）と投資信託の違い・税金・分配金を徹底比較。あなたに合う方がわかる。",
    icon: "📊",
    category: "nisa",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "investment-complete-guide",
    title: "【投資完全ガイド】初心者が最初に読むべき資産運用の全て",
    description: "投資初心者向けの完全ガイド。新NISA・iDeCo・株・FX・仮想通貨・不動産まで、全資産クラスの特徴・始め方・リスク管理を一気に理解できる。",
    icon: "📚",
    category: "nisa",
    readTime: "25分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "money-basics-guide",
    title: "【お金の基礎】貯金・投資・保険の正しい組合せ方",
    description: "お金の増やし方・守り方を総合的に解説。生活防衛資金・投資・保険のバランスを年代別・家族構成別にアドバイス。",
    icon: "💰",
    category: "household",
    readTime: "20分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "retirement-planning-guide",
    title: "【老後資金完全ガイド】2,000万円問題の解決策",
    description: "老後に本当に必要な金額と、今からできる具体的な準備方法。年齢別・収入別のシミュレーションで老後不安を解消。",
    icon: "👴",
    category: "nisa",
    readTime: "22分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "nisa-growth-vs-tsumitate",
    title: "新NISA成長投資枠 vs つみたて投資枠｜使い分け完全ガイド",
    description: "年間240万円の成長枠と120万円のつみたて枠、どう使い分ける？年収別・目的別の最適な配分を解説。",
    icon: "⚖️",
    category: "nisa",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "credit-card-stacking",
    title: "クレカ積立フル活用術｜月10万円×3社で最大3,600P獲得",
    description: "SBI・楽天・マネックスの3社でクレカ積立を併用すると月30万円まで対応可能。最大限のポイントを貯める方法。",
    icon: "💳",
    category: "card",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "sbi-securities-for-beginners",
    title: "SBI証券で新NISAを始める手順｜口座開設から積立設定まで",
    description: "SBI証券で新NISA口座を開設する手順を画面つきで解説。三井住友カード連携・積立設定・銘柄選びまでを網羅。",
    icon: "📝",
    category: "broker",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "rakuten-securities-for-beginners",
    title: "楽天証券で新NISAを始める手順｜初心者でも10分で完了",
    description: "楽天証券の口座開設から新NISA積立開始までを画面つきで解説。楽天カード積立・マネーブリッジ設定も。",
    icon: "📝",
    category: "broker",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "foreign-dividend-stocks",
    title: "米国高配当株投資の始め方｜配当金生活への道筋",
    description: "VYM・HDV・SPYD等の米国高配当ETFで不労所得を作る方法。税金・為替リスク・おすすめ証券会社を解説。",
    icon: "💵",
    category: "broker",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "ideco-vs-corporate-pension",
    title: "iDeCo vs 企業型DC｜会社員はどっちが有利？",
    description: "iDeCoと企業型確定拠出年金の違いを比較。マッチング拠出の効果、転職時の移換手続きも解説。",
    icon: "🏦",
    category: "ideco",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "taxable-vs-nisa",
    title: "特定口座 vs NISA口座｜使い分けで税金をゼロに",
    description: "特定口座と新NISA口座の違いを徹底解説。税金20.315%を回避しつつ、投資枠を最大限活用する方法。",
    icon: "📊",
    category: "broker",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "fx-vs-stock-vs-crypto",
    title: "FX・株・仮想通貨｜リターンとリスクの正しい比較",
    description: "代表的な投資先3つのリターン・ボラティリティ・税制・流動性を比較。自分に合う投資を見つける方法。",
    icon: "⚖️",
    category: "fx-crypto",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "year-end-tax-saving",
    title: "【年末の節税】12月までにやるべき6つのこと",
    description: "ふるさと納税・iDeCo拠出・NISA使い切り・損益通算など、年末までに済ませるべき節税アクションを網羅。",
    icon: "📅",
    category: "household",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "emergency-fund-strategy",
    title: "生活防衛資金の貯め方｜何ヶ月分必要？どこに預ける？",
    description: "生活防衛資金の目安額と、普通預金・ネット銀行・MMFなど最適な保管場所を解説。",
    icon: "🛟",
    category: "household",
    readTime: "9分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "junior-nisa-successor",
    title: "2024年廃止のジュニアNISA後継｜子どもの教育資金戦略",
    description: "ジュニアNISA廃止後の教育資金準備方法。新NISA・学資保険・贈与の最適な組合せを解説。",
    icon: "👶",
    category: "household",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "ipo-investment-guide",
    title: "【2026年版】IPO投資完全ガイド｜当選確率を上げる証券会社選び",
    description: "IPO（新規公開株）投資の仕組み・抽選方法・主幹事実績で選ぶ証券会社を徹底解説。初値益を狙う初心者向け戦略。",
    icon: "🚀",
    category: "broker",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "high-dividend-stocks-guide",
    title: "【2026年】高配当株投資で月5万円の配当金を得る方法",
    description: "日本株・米国株の高配当銘柄の選び方、利回り計算、NISAと組み合わせる節税戦略。配当金生活を目指すロードマップ。",
    icon: "💵",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "dividend-life-roadmap",
    title: "配当金生活を実現するロードマップ｜必要な投資額と戦略",
    description: "月10万円/20万円/30万円の配当金を得るために必要な投資額と、年代別・収入別の実現プラン。FIRE達成を目指す人向け。",
    icon: "🏖️",
    category: "nisa",
    readTime: "14分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "us-stock-investment-guide",
    title: "米国株投資完全ガイド｜S&P500・高配当・成長株の選び方",
    description: "米国株投資の始め方、S&P500インデックス・高配当ETF（VYM/SPYD）・個別株（GAFAM）の使い分けを初心者向けに解説。",
    icon: "🇺🇸",
    category: "nisa",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "gold-investment-guide",
    title: "金投資の始め方｜純金積立・金ETF・金地金の比較",
    description: "インフレ対策として注目される金投資。純金積立、金ETF、金地金購入のメリット・デメリットと最適な配分を解説。",
    icon: "🪙",
    category: "nisa",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "bond-investment-beginners",
    title: "債券投資入門｜国債・社債・外債の違いとポートフォリオ活用術",
    description: "低リスク・安定収益の債券投資の基礎。個人向け国債、社債、米国債の選び方と株式との最適な組合せ。",
    icon: "📜",
    category: "nisa",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "reit-investment-guide",
    title: "J-REIT投資ガイド｜不動産投資信託で分配金収入を得る方法",
    description: "J-REITの仕組み、主要銘柄の比較、NISA活用での非課税運用、不動産クラウドファンディングとの違いを解説。",
    icon: "🏢",
    category: "nisa",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "insurance-optimization-guide",
    title: "会社員のための保険見直しガイド｜本当に必要な保障額の計算方法",
    description: "生命保険・医療保険・がん保険の必要保障額を家族構成・年収別に試算。公的保障を考慮した最適な保険選びを解説。",
    icon: "🛡️",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "fx-vps-guide",
    title: "FX自動売買のためのVPS選び完全ガイド",
    description: "24時間MT4/MT5を稼働させるためのFX専用VPS比較。お名前.com・ABLEネット・お名前デスクトップクラウドの違いを徹底解説。",
    icon: "🖥️",
    category: "fx-crypto",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "investment-school-comparison",
    title: "投資スクール徹底比較｜ファイナンシャルアカデミー・Global Financial School他",
    description: "投資を本格的に学ぶ投資スクールを比較。受講料・カリキュラム・実績・無料体験の有無を初心者向けに解説。",
    icon: "🎓",
    category: "nisa",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "cashing-comparison-guide",
    title: "【2026年】消費者金融・キャッシング徹底比較｜即日融資可能な7社",
    description: "セントラル・フタバ・アイフル・アコムなど主要消費者金融の金利・限度額・審査時間を比較。即日融資のコツと選び方。",
    icon: "💸",
    category: "household",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "factoring-comparison-guide",
    title: "ファクタリング徹底比較｜法人・個人事業主の資金調達ガイド",
    description: "トップ・マネジメント・資金調達プロなど主要ファクタリングサービスを比較。手数料・最短入金時間・利用条件を初めての方向けに解説。",
    icon: "💼",
    category: "business",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "investment-books-2026",
    title: "【2026年】投資初心者が読むべきおすすめ投資本10選",
    description: "新NISA時代に読みたい投資本を厳選。お金の大学・ジェイソン流・金持ち父さん・サイコロジーオブマネーなど定番から最新刊まで。楽天ブックスで送料無料・ポイント還元で買える。",
    icon: "📚",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "net-bank-comparison-2026",
    title: "【2026年】ネット銀行おすすめ比較｜住信SBI・楽天・auじぶん・PayPay銀行",
    description: "金利・ATM手数料・振込手数料・連携サービスを主要ネット銀行6社で徹底比較。新NISA・投資・給与受取・サブ口座におすすめの銀行がわかる。",
    icon: "🏦",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "rakuten-economic-zone-2026",
    title: "【2026年】楽天経済圏完全攻略ガイド｜SPU最大化と年間10万ポイント獲得法",
    description: "楽天カード・楽天銀行・楽天証券・楽天モバイル・楽天市場の連携で年10万円相当の楽天ポイントを獲得する方法。SPU倍率の最大化・お買い物マラソン・ふるさと納税活用まで。",
    icon: "🎖️",
    category: "card",
    readTime: "14分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "investment-fund-comparison-2026",
    title: "【2026年】投資信託おすすめ比較｜eMAXIS Slim・SBI V・ニッセイ",
    description: "新NISAで積立すべき投資信託を信託報酬・運用実績・純資産額で比較。オルカン・S&P500・NASDAQ100・全米株式の違いと最適な配分を初心者向けに解説。",
    icon: "📊",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "insurance-comparison-2026",
    title: "【2026年】生命保険おすすめ比較｜会社員向け保障額と選び方",
    description: "生命保険・医療保険・がん保険・就業不能保険の必要性と選び方。公的保障を前提にした最小限の保険設計を家族構成別に解説。",
    icon: "🛡️",
    category: "household",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "tax-saving-salary-income",
    title: "【2026年】会社員ができる節税術10選｜年間30万円の手取りアップ",
    description: "iDeCo・新NISA・ふるさと納税・医療費控除・特定支出控除・副業経費計上まで。会社員でも年30万円以上の手取り増加を実現する合法節税術を網羅。",
    icon: "💡",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "mortgage-comparison-2026",
    title: "【2026年】住宅ローンおすすめ比較｜変動金利・固定金利・フラット35",
    description: "住信SBI・楽天銀行・auじぶん・PayPay・ソニー銀行・ARUHIの金利・団信・事務手数料を比較。変動0.3%台・フラット35・一括比較サービスの活用まで。",
    icon: "🏠",
    category: "household",
    readTime: "14分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "medical-insurance-comparison-2026",
    title: "【2026年】医療保険・がん保険おすすめ比較｜必要な保障額と選び方",
    description: "アフラック・オリックス・チューリッヒ・メディケア生命・県民共済の医療保険・がん保険を比較。公的医療保険との併用で月1,000円から最適な備えを構築。",
    icon: "🏥",
    category: "household",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "investing-50s-strategy",
    title: "【2026年】50代の資産運用戦略｜定年までの10年で1,500万円を作る",
    description: "50代からの新NISA・iDeCo・退職金運用の最適解。守りと攻めのバランス、60歳出口戦略、高配当株・債券・ロボアドの使い分けを解説。",
    icon: "🎯",
    category: "nisa",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "nisa-ideco-combined-strategy",
    title: "【2026年】新NISA×iDeCo 併用完全ガイド｜年齢別の優先順位と最強配分",
    description: "新NISAとiDeCoの違い・併用メリット・年代別優先順位を徹底解説。年収500万/800万/1,200万の3モデルで最適配分シミュレーション付き。",
    icon: "⚖️",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "housewife-investment-guide",
    title: "【2026年】主婦・主夫のための投資と副業ガイド｜103万・150万の壁と新NISA",
    description: "扶養内の主婦・主夫が知っておくべき新NISA・クレカ積立・在宅副業の始め方。103万/130万/150万円の壁を超えない範囲での収入アップ戦略。",
    icon: "👩",
    category: "sidejob",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "mortgage-refinance-guide",
    title: "【2026年】住宅ローン借り換え完全ガイド｜総返済額300万円減の実例",
    description: "変動0.3%台の今こそ借り換え好機。残高1,500万円以上・残期間10年以上・金利差1%以上なら総返済額で200〜500万円減。諸費用・団信切替・審査通過のコツを実例で解説。",
    icon: "♻️",
    category: "household",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "social-lending-comparison",
    title: "【2026年】ソーシャルレンディング比較｜Funds・SBI SL・クラウドバンク",
    description: "利回り4〜8%の貸付型クラウドファンディング主要5社を比較。Funds・SBIソーシャルレンディング・クラウドバンク・Crowd Realty・OwnersBookの案件タイプ・手数料・リスクを解説。",
    icon: "🏦",
    category: "fx-crypto",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "education-insurance-comparison",
    title: "【2026年】学資保険おすすめ比較｜ソニー生命・明治安田・日本生命",
    description: "返戻率105〜108%の学資保険主要5社を比較。新NISA成長投資枠との比較、払込期間・受取方法の選び方、子供の年齢別おすすめプランを解説。",
    icon: "🎓",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "tax-filing-software-comparison",
    title: "【2026年】確定申告ソフト比較｜freee・弥生・マネーフォワード",
    description: "副業・フリーランス向け確定申告ソフト3大サービスを料金・使いやすさ・機能で徹底比較。青色申告65万円控除を取るための最適な選び方を解説。",
    icon: "📝",
    category: "sidejob",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "inheritance-planning-guide",
    title: "【2026年】相続対策・生前贈与完全ガイド｜年110万円非課税枠と相続時精算課税",
    description: "暦年贈与・相続時精算課税・教育資金一括贈与の3制度を徹底解説。2024年改正で生前贈与7年加算に強化。不動産・生命保険を活用した節税スキームまで。",
    icon: "🎁",
    category: "household",
    readTime: "14分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "retirement-2000-man-complete-guide",
    title: "【2026年】老後2000万円問題 完全対策ガイド｜世帯別必要額と準備シミュレーション",
    description: "老後2000万円問題は本当か？年金受給額・生活費・介護費用から逆算した必要資金を世帯別に試算。新NISA・iDeCo・退職金・個人年金を組み合わせた準備法。",
    icon: "👴",
    category: "nisa",
    readTime: "14分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "nisa-withdrawal-strategy",
    title: "【2026年】新NISA 出口戦略完全ガイド｜取り崩しの4%ルールと税務",
    description: "新NISAで築いた資産をいつ・どう取り崩すか。4%ルール・バケツ戦略・定率取崩の3手法を解説。65歳リタイア・70歳繰下げ年金との最適な組み合わせ。",
    icon: "🏁",
    category: "nisa",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "takehome-maximize-by-income",
    title: "【2026年】年収別 手取り最大化戦略｜年収400/600/800/1000万円モデル",
    description: "iDeCo・ふるさと納税・新NISAを年収別にフル活用した手取り最大化シミュレーション。年収400万〜1,200万円の4パターンで具体的な節税額を試算。",
    icon: "💸",
    category: "household",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "bitcoin-long-term-strategy",
    title: "【2026年】ビットコイン長期保有戦略｜ドルコスト平均法と税務",
    description: "ビットコインを10年ガチホするならどう買うか。ドルコスト平均法・時間分散・半減期サイクル・取引所セキュリティ・税金対策を実践的に解説。",
    icon: "₿",
    category: "fx-crypto",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "blog-side-income-roadmap",
    title: "【2026年】副業ブログ収益化完全ロードマップ｜月10万円への最短ルート",
    description: "ブログ副業で月10万円を達成するまでの12ヶ月ロードマップ。ジャンル選定・WordPress構築・SEO・ASP選び・記事設計の実践マニュアル。",
    icon: "✍️",
    category: "sidejob",
    readTime: "15分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "business-card-comparison-2026",
    title: "【2026年】法人・個人事業主向けビジネスカードおすすめ比較10選",
    description: "個人事業主・中小企業経営者向けにビジネスカードを徹底比較。freeeカード・三井住友カードビジネス・楽天ビジネス・JCBビジネス等、年会費/還元率/限度額/付帯サービスで選ぶ。",
    icon: "🏢",
    category: "card",
    readTime: "13分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "fp-consultation-guide",
    title: "【2026年】FP無料相談おすすめ比較｜保険・資産運用・住宅ローンの無料アドバイス",
    description: "保険見直しラボ・マネプロ・ほけんのトータルプロフェッショナル等、FP無料相談サービスを徹底比較。相談の流れ・断り方・おすすめの活用法まで解説。",
    icon: "🧑‍💼",
    category: "household",
    readTime: "11分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "dual-income-household-guide",
    title: "【2026年】共働き夫婦の資産運用ロードマップ｜世帯年収別の最適プラン",
    description: "世帯年収700万〜1500万円の共働き夫婦向け、新NISA・iDeCo・クレカ積立・児童手当を組み合わせた最適資産運用戦略。夫婦別口座・家計の折半方法も解説。",
    icon: "👫",
    category: "nisa",
    readTime: "14分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "real-estate-crowdfunding-comparison-2026",
    title: "【2026年】不動産クラウドファンディング比較10社｜利回り・最低投資額・実績",
    description: "COZUCHI・CREAL・利回りくん・OwnersBook等の不動産クラファン10社を徹底比較。想定利回り4〜10%、1万円から始められる新しい投資法。元本保全性・運営会社の実績で選ぶ。",
    icon: "🏢",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "tax-accountant-consultation-guide",
    title: "【2026年】税理士無料相談おすすめ比較｜個人事業主・フリーランス向け",
    description: "税理士ドットコム・税理士紹介ネットワーク・freee税理士検索を比較。確定申告・インボイス対応・節税コンサルまで、個人事業主向けに最適な税理士の選び方。",
    icon: "👔",
    category: "sidejob",
    readTime: "11分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "high-income-tax-strategy",
    title: "【2026年】年収1000万円超の節税戦略｜実践的な手取り最大化マニュアル",
    description: "年収1000万〜2000万円の高所得者向け節税マニュアル。iDeCo/小規模共済/ふるさと納税/生命保険/不動産投資/医療費控除を組み合わせて年100万円超の節税を実現する方法。",
    icon: "💰",
    category: "household",
    readTime: "15分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "fixed-cost-reduction-guide",
    title: "【2026年】固定費削減完全マニュアル｜年30万円以上の節約術",
    description: "通信費・保険・サブスク・光熱費・住居費を見直して年30万円以上節約。格安SIM乗換・保険見直し・電力自由化活用で実現する具体的手順を解説。",
    icon: "✂️",
    category: "household",
    readTime: "14分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "early-career-investment-roadmap",
    title: "【2026年】20代新社会人の資産形成ロードマップ｜月3万円から始める10年プラン",
    description: "20代の新社会人向け、月3万円から始める資産形成の10年ロードマップ。新NISAつみたて投資枠の活用法・固定費最適化・副業でのブースト戦略まで。",
    icon: "🌱",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "auto-insurance-comparison-2026",
    title: "【2026年】自動車保険おすすめ比較10社｜ネット型 vs 代理店型で年3万円節約",
    description: "ソニー損保・SBI損保・チューリッヒ・アクサダイレクト等のダイレクト型自動車保険を徹底比較。等級・車種・年齢別の保険料シミュレーション、代理店型との違いを解説。",
    icon: "🚗",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "ifa-service-comparison",
    title: "【2026年】IFA（独立系FA）おすすめ比較｜富裕層向け資産運用パートナー",
    description: "IFA（Independent Financial Advisor）の選び方とおすすめ事務所を徹底比較。証券会社よりも中立的な資産運用アドバイス、1億円以上の運用に強いIFAとの出会い方。",
    icon: "💼",
    category: "nisa",
    readTime: "12分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "freelance-retirement-guide",
    title: "【2026年】フリーランス・個人事業主の年金完全ガイド｜iDeCo/付加年金/国民年金基金",
    description: "会社員の3分の1しかない国民年金（老齢基礎年金）を補完する、フリーランスの年金戦略。iDeCo月6.8万円・付加年金・国民年金基金・小規模企業共済を組合せて老後月25万円を実現する方法。",
    icon: "👴",
    category: "ideco",
    readTime: "13分",
    publishedAt: "2026-04-19",
  },
];

export function getGuideBySlug(slug: string) {
  return guides.find((g) => g.slug === slug);
}
