export interface Guide {
  slug: string;
  title: string;
  description: string;
  icon: string;
  category: string;
  readTime: string;
  publishedAt: string;
}

export const guides: Guide[] = [
  {
    slug: "nisa-broker-ranking-2026",
    title: "【2026年】新NISAおすすめネット証券ランキングTOP5",
    description: "SBI証券・楽天証券・マネックス証券など主要ネット証券の新NISA対応状況・ポイント還元・取扱銘柄数を徹底比較。初心者におすすめの口座を紹介。",
    icon: "💰",
    category: "nisa",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "roboadvisor-comparison",
    title: "【2026年】ロボアドバイザーおすすめ比較5社",
    description: "ウェルスナビ・THEO・楽ラップ・SUSTEN・ON COMPASSの手数料・運用実績・最低投資額を比較。初心者に最適なロボアドを解説。",
    icon: "🤖",
    category: "roboadvisor",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "ideco-broker-comparison",
    title: "【2026年】iDeCoおすすめ金融機関比較",
    description: "SBI証券・楽天証券・マネックス証券・松井証券のiDeCo手数料・取扱商品数を比較。節税効果を最大化する選び方を解説。",
    icon: "🏦",
    category: "ideco",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "fx-broker-ranking",
    title: "【2026年】FX口座開設キャンペーン比較TOP10",
    description: "GMOクリック・DMM FX・外為どっとコムなど主要FX会社のスプレッド・スワップ・キャンペーン特典を比較。",
    icon: "💹",
    category: "fx-crypto",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "crypto-exchange-comparison",
    title: "【2026年】仮想通貨取引所おすすめ比較",
    description: "bitFlyer・コインチェック・GMOコイン・bitbankの手数料・取扱通貨・セキュリティを比較。初心者におすすめの取引所を紹介。",
    icon: "₿",
    category: "fx-crypto",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "high-reward-credit-cards",
    title: "【2026年】高還元率クレジットカードおすすめ10選",
    description: "還元率1%以上の年会費無料カードから、投資積立で還元を受けられるカードまで。目的別の選び方を解説。",
    icon: "💳",
    category: "card",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "side-business-ranking-2026",
    title: "【2026年】会社員におすすめの副業ランキングTOP10",
    description: "月5万円から狙える副業を厳選。初期費用・必要スキル・想定収入・確定申告の必要性まで徹底解説。",
    icon: "💼",
    category: "sidejob",
    readTime: "15分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "household-budget-apps",
    title: "【2026年】家計簿アプリおすすめ比較",
    description: "マネーフォワードME・Zaim・Money Tree・おかねのコンパスの機能・料金・連携数を比較。無料で使える定番を紹介。",
    icon: "📝",
    category: "household",
    readTime: "8分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "new-nisa-basics",
    title: "新NISA完全ガイド｜始め方・おすすめ銘柄・注意点",
    description: "2024年から始まった新NISAの制度を初心者向けに徹底解説。つみたて投資枠・成長投資枠の使い分けとおすすめ銘柄を紹介。",
    icon: "📖",
    category: "nisa",
    readTime: "15分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "fire-guide",
    title: "【FIRE完全ガイド】40代で経済的自立を達成する方法",
    description: "FIRE（経済的自立と早期退職）達成までの資産目標額、投資戦略、収入増加術を解説。日本人の実例付き。",
    icon: "🔥",
    category: "nisa",
    readTime: "18分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "tax-saving-techniques",
    title: "会社員ができる節税テクニック完全ガイド",
    description: "ふるさと納税・iDeCo・住宅ローン控除・医療費控除など、会社員でも使える節税制度を総まとめ。",
    icon: "💸",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "online-bank-comparison",
    title: "【2026年】ネット銀行金利・手数料比較",
    description: "住信SBIネット銀行・楽天銀行・auじぶん銀行・PayPay銀行の金利・ATM手数料・振込特典を比較。",
    icon: "🏧",
    category: "household",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "sbi-vs-rakuten-nisa",
    title: "SBI証券 vs 楽天証券｜新NISAはどっちがお得？完全比較",
    description: "ネット証券2強のSBI証券と楽天証券を新NISA目線で徹底比較。クレカ積立還元率・ポイント・アプリ使いやすさまで全項目を検証。",
    icon: "⚔️",
    category: "broker",
    readTime: "14分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "furusato-tax-guide-2026",
    title: "【2026年】ふるさと納税完全ガイド｜限度額・おすすめサイト・返礼品",
    description: "ふるさと納税の仕組みから限度額計算、おすすめポータルサイトまで。実質2,000円で返礼品を受け取る方法を解説。",
    icon: "🎁",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "side-business-tax-declaration",
    title: "会社員の副業確定申告ガイド｜20万円ルール・やり方・経費",
    description: "副業収入がある会社員向けに確定申告の必要性・計算方法・経費計上のコツを解説。年間20万円ルールの注意点も。",
    icon: "📋",
    category: "sidejob",
    readTime: "15分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "wealthnavi-vs-theo",
    title: "ウェルスナビ vs THEO｜ロボアド2大サービス徹底比較",
    description: "ロボアドバイザー大手ウェルスナビとTHEOの手数料・運用実績・機能を比較。どちらを選ぶべきかを徹底解説。",
    icon: "🤖",
    category: "roboadvisor",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "crypto-tax-guide",
    title: "仮想通貨の税金完全ガイド｜雑所得の計算方法と節税対策",
    description: "ビットコイン等の仮想通貨で利益が出た場合の税金計算。雑所得の累進課税、損益通算の可否、節税のコツを解説。",
    icon: "💰",
    category: "fx-crypto",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "sbi-securities-review",
    title: "SBI証券の評判・メリット・デメリット｜実際の使用レビュー",
    description: "国内ネット証券口座数No.1のSBI証券を徹底レビュー。手数料・取扱銘柄・アプリの使いやすさまで実体験ベースで解説。",
    icon: "📊",
    category: "broker",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "high-yield-stock-strategy",
    title: "高配当株投資の始め方｜日本株・米国株のおすすめ銘柄",
    description: "配当利回り4%以上の高配当株で不労所得を作る方法。日本高配当株・米国ETFのおすすめと注意点を解説。",
    icon: "💵",
    category: "broker",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "rakuten-securities-review",
    title: "楽天証券の評判・メリット・デメリット｜実際の使用レビュー",
    description: "楽天経済圏ユーザー必見。楽天証券の手数料・ポイント還元・アプリ使いやすさを徹底レビュー。",
    icon: "📊",
    category: "broker",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "monex-securities-review",
    title: "マネックス証券の評判｜クレカ積立1.1%還元の実力",
    description: "マネックスカード積立で業界最高水準1.1%還元のマネックス証券を徹底レビュー。米国株の強みも解説。",
    icon: "📊",
    category: "broker",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "gmo-click-fx-review",
    title: "GMOクリック証券FX徹底レビュー｜国内口座数No.1の理由",
    description: "FX口座開設数国内No.1のGMOクリック証券を徹底解説。スプレッド・スワップ・キャンペーンを検証。",
    icon: "💹",
    category: "fx-crypto",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "dmm-fx-review",
    title: "DMM FX徹底レビュー｜キャッシュバック最大30万円の全条件",
    description: "DMM FXの新規口座開設キャンペーンで最大30万円のキャッシュバックを受ける条件を完全解説。",
    icon: "💹",
    category: "fx-crypto",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "bitflyer-review",
    title: "bitFlyer徹底レビュー｜国内最大手仮想通貨取引所の全貌",
    description: "ビットコイン取引量国内No.1のbitFlyerを徹底解説。手数料・セキュリティ・使いやすさを検証。",
    icon: "₿",
    category: "fx-crypto",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "coincheck-review",
    title: "コインチェック徹底レビュー｜初心者に人気No.1の理由",
    description: "アプリDL数No.1のコインチェックを解説。取扱通貨・手数料・セキュリティを詳しくレビュー。",
    icon: "₿",
    category: "fx-crypto",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "investing-30s-strategy",
    title: "30代から始める投資戦略｜月3万円で将来4,000万円",
    description: "30代会社員向け投資戦略。新NISA・iDeCo・高配当株の組合せで65歳までに4,000万円を作る方法。",
    icon: "📈",
    category: "nisa",
    readTime: "14分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "investing-40s-strategy",
    title: "40代から始める投資戦略｜遅くない！老後資金2,000万円確保",
    description: "40代からでも間に合う投資戦略。限られた時間で効率的に資産形成する方法を年代別に解説。",
    icon: "📈",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "real-estate-crowdfunding",
    title: "不動産クラウドファンディング比較｜1万円から始める不動産投資",
    description: "COZUCHI・CREAL・Funds等の不動産クラウドファンディングを比較。利回り・最低投資額・リスクを解説。",
    icon: "🏠",
    category: "broker",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "insurance-life-comparison",
    title: "生命保険の選び方｜独身・既婚別のおすすめと見直しポイント",
    description: "生命保険の必要性・種類・選び方を解説。ライフステージ別のおすすめ保険金額と保険料の目安を紹介。",
    icon: "🛡️",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "kids-education-fund",
    title: "教育資金準備ガイド｜学資保険 vs NISA、どっちがお得？",
    description: "子どもの教育資金を準備する方法を比較。学資保険と新NISAつみたて投資枠のメリット・デメリット。",
    icon: "🎓",
    category: "household",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "crowdworks-vs-lancers",
    title: "クラウドワークス vs ランサーズ｜会社員の副業おすすめは？",
    description: "国内2大クラウドソーシングを徹底比較。手数料・案件数・稼ぎやすさを会社員副業目線で解説。",
    icon: "💼",
    category: "sidejob",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "blog-side-business",
    title: "ブログ副業で月5万円稼ぐ方法｜WordPress・アフィリエイト入門",
    description: "会社員がブログ副業で月5万円を稼ぐまでのロードマップ。WordPress設定から収益化までを解説。",
    icon: "💻",
    category: "sidejob",
    readTime: "15分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "stock-beginner-guide",
    title: "株式投資の始め方｜初心者が失敗しない7つのルール",
    description: "株式投資初心者が知っておきたい基礎知識と失敗しないためのルール。銘柄選びから売買タイミングまで。",
    icon: "📊",
    category: "broker",
    readTime: "14分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "etf-vs-mutual-fund",
    title: "ETF vs 投資信託｜どっちを選ぶ？メリット・デメリット比較",
    description: "ETF（上場投資信託）と投資信託の違い・税金・分配金を徹底比較。あなたに合う方がわかる。",
    icon: "📊",
    category: "nisa",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "investment-complete-guide",
    title: "【投資完全ガイド】初心者が最初に読むべき資産運用の全て",
    description: "投資初心者向けの完全ガイド。新NISA・iDeCo・株・FX・仮想通貨・不動産まで、全資産クラスの特徴・始め方・リスク管理を一気に理解できる。",
    icon: "📚",
    category: "nisa",
    readTime: "25分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "money-basics-guide",
    title: "【お金の基礎】貯金・投資・保険の正しい組合せ方",
    description: "お金の増やし方・守り方を総合的に解説。生活防衛資金・投資・保険のバランスを年代別・家族構成別にアドバイス。",
    icon: "💰",
    category: "household",
    readTime: "20分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "retirement-planning-guide",
    title: "【老後資金完全ガイド】2,000万円問題の解決策",
    description: "老後に本当に必要な金額と、今からできる具体的な準備方法。年齢別・収入別のシミュレーションで老後不安を解消。",
    icon: "👴",
    category: "nisa",
    readTime: "22分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "nisa-growth-vs-tsumitate",
    title: "新NISA成長投資枠 vs つみたて投資枠｜使い分け完全ガイド",
    description: "年間240万円の成長枠と120万円のつみたて枠、どう使い分ける？年収別・目的別の最適な配分を解説。",
    icon: "⚖️",
    category: "nisa",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "credit-card-stacking",
    title: "クレカ積立フル活用術｜月10万円×3社で最大3,600P獲得",
    description: "SBI・楽天・マネックスの3社でクレカ積立を併用すると月30万円まで対応可能。最大限のポイントを貯める方法。",
    icon: "💳",
    category: "card",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "sbi-securities-for-beginners",
    title: "SBI証券で新NISAを始める手順｜口座開設から積立設定まで",
    description: "SBI証券で新NISA口座を開設する手順を画面つきで解説。三井住友カード連携・積立設定・銘柄選びまでを網羅。",
    icon: "📝",
    category: "broker",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "rakuten-securities-for-beginners",
    title: "楽天証券で新NISAを始める手順｜初心者でも10分で完了",
    description: "楽天証券の口座開設から新NISA積立開始までを画面つきで解説。楽天カード積立・マネーブリッジ設定も。",
    icon: "📝",
    category: "broker",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "foreign-dividend-stocks",
    title: "米国高配当株投資の始め方｜配当金生活への道筋",
    description: "VYM・HDV・SPYD等の米国高配当ETFで不労所得を作る方法。税金・為替リスク・おすすめ証券会社を解説。",
    icon: "💵",
    category: "broker",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "ideco-vs-corporate-pension",
    title: "iDeCo vs 企業型DC｜会社員はどっちが有利？",
    description: "iDeCoと企業型確定拠出年金の違いを比較。マッチング拠出の効果、転職時の移換手続きも解説。",
    icon: "🏦",
    category: "ideco",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "taxable-vs-nisa",
    title: "特定口座 vs NISA口座｜使い分けで税金をゼロに",
    description: "特定口座と新NISA口座の違いを徹底解説。税金20.315%を回避しつつ、投資枠を最大限活用する方法。",
    icon: "📊",
    category: "broker",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "fx-vs-stock-vs-crypto",
    title: "FX・株・仮想通貨｜リターンとリスクの正しい比較",
    description: "代表的な投資先3つのリターン・ボラティリティ・税制・流動性を比較。自分に合う投資を見つける方法。",
    icon: "⚖️",
    category: "fx-crypto",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "year-end-tax-saving",
    title: "【年末の節税】12月までにやるべき6つのこと",
    description: "ふるさと納税・iDeCo拠出・NISA使い切り・損益通算など、年末までに済ませるべき節税アクションを網羅。",
    icon: "📅",
    category: "household",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "emergency-fund-strategy",
    title: "生活防衛資金の貯め方｜何ヶ月分必要？どこに預ける？",
    description: "生活防衛資金の目安額と、普通預金・ネット銀行・MMFなど最適な保管場所を解説。",
    icon: "🛟",
    category: "household",
    readTime: "9分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "junior-nisa-successor",
    title: "2024年廃止のジュニアNISA後継｜子どもの教育資金戦略",
    description: "ジュニアNISA廃止後の教育資金準備方法。新NISA・学資保険・贈与の最適な組合せを解説。",
    icon: "👶",
    category: "household",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "ipo-investment-guide",
    title: "【2026年版】IPO投資完全ガイド｜当選確率を上げる証券会社選び",
    description: "IPO（新規公開株）投資の仕組み・抽選方法・主幹事実績で選ぶ証券会社を徹底解説。初値益を狙う初心者向け戦略。",
    icon: "🚀",
    category: "broker",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "high-dividend-stocks-guide",
    title: "【2026年】高配当株投資で月5万円の配当金を得る方法",
    description: "日本株・米国株の高配当銘柄の選び方、利回り計算、NISAと組み合わせる節税戦略。配当金生活を目指すロードマップ。",
    icon: "💵",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "dividend-life-roadmap",
    title: "配当金生活を実現するロードマップ｜必要な投資額と戦略",
    description: "月10万円/20万円/30万円の配当金を得るために必要な投資額と、年代別・収入別の実現プラン。FIRE達成を目指す人向け。",
    icon: "🏖️",
    category: "nisa",
    readTime: "14分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "us-stock-investment-guide",
    title: "米国株投資完全ガイド｜S&P500・高配当・成長株の選び方",
    description: "米国株投資の始め方、S&P500インデックス・高配当ETF（VYM/SPYD）・個別株（GAFAM）の使い分けを初心者向けに解説。",
    icon: "🇺🇸",
    category: "nisa",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "gold-investment-guide",
    title: "金投資の始め方｜純金積立・金ETF・金地金の比較",
    description: "インフレ対策として注目される金投資。純金積立、金ETF、金地金購入のメリット・デメリットと最適な配分を解説。",
    icon: "🪙",
    category: "nisa",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "bond-investment-beginners",
    title: "債券投資入門｜国債・社債・外債の違いとポートフォリオ活用術",
    description: "低リスク・安定収益の債券投資の基礎。個人向け国債、社債、米国債の選び方と株式との最適な組合せ。",
    icon: "📜",
    category: "nisa",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "reit-investment-guide",
    title: "J-REIT投資ガイド｜不動産投資信託で分配金収入を得る方法",
    description: "J-REITの仕組み、主要銘柄の比較、NISA活用での非課税運用、不動産クラウドファンディングとの違いを解説。",
    icon: "🏢",
    category: "nisa",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "insurance-optimization-guide",
    title: "会社員のための保険見直しガイド｜本当に必要な保障額の計算方法",
    description: "生命保険・医療保険・がん保険の必要保障額を家族構成・年収別に試算。公的保障を考慮した最適な保険選びを解説。",
    icon: "🛡️",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "fx-vps-guide",
    title: "FX自動売買のためのVPS選び完全ガイド",
    description: "24時間MT4/MT5を稼働させるためのFX専用VPS比較。お名前.com・ABLEネット・お名前デスクトップクラウドの違いを徹底解説。",
    icon: "🖥️",
    category: "fx-crypto",
    readTime: "10分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "investment-school-comparison",
    title: "投資スクール徹底比較｜ファイナンシャルアカデミー・Global Financial School他",
    description: "投資を本格的に学ぶ投資スクールを比較。受講料・カリキュラム・実績・無料体験の有無を初心者向けに解説。",
    icon: "🎓",
    category: "nisa",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "cashing-comparison-guide",
    title: "【2026年】消費者金融・キャッシング徹底比較｜即日融資可能な7社",
    description: "セントラル・フタバ・アイフル・アコムなど主要消費者金融の金利・限度額・審査時間を比較。即日融資のコツと選び方。",
    icon: "💸",
    category: "household",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "factoring-comparison-guide",
    title: "ファクタリング徹底比較｜法人・個人事業主の資金調達ガイド",
    description: "トップ・マネジメント・資金調達プロなど主要ファクタリングサービスを比較。手数料・最短入金時間・利用条件を初めての方向けに解説。",
    icon: "💼",
    category: "business",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "investment-books-2026",
    title: "【2026年】投資初心者が読むべきおすすめ投資本10選",
    description: "新NISA時代に読みたい投資本を厳選。お金の大学・ジェイソン流・金持ち父さん・サイコロジーオブマネーなど定番から最新刊まで。楽天ブックスで送料無料・ポイント還元で買える。",
    icon: "📚",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "net-bank-comparison-2026",
    title: "【2026年】ネット銀行おすすめ比較｜住信SBI・楽天・auじぶん・PayPay銀行",
    description: "金利・ATM手数料・振込手数料・連携サービスを主要ネット銀行6社で徹底比較。新NISA・投資・給与受取・サブ口座におすすめの銀行がわかる。",
    icon: "🏦",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "rakuten-economic-zone-2026",
    title: "【2026年】楽天経済圏完全攻略ガイド｜SPU最大化と年間10万ポイント獲得法",
    description: "楽天カード・楽天銀行・楽天証券・楽天モバイル・楽天市場の連携で年10万円相当の楽天ポイントを獲得する方法。SPU倍率の最大化・お買い物マラソン・ふるさと納税活用まで。",
    icon: "🎖️",
    category: "card",
    readTime: "14分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "investment-fund-comparison-2026",
    title: "【2026年】投資信託おすすめ比較｜eMAXIS Slim・SBI V・ニッセイ",
    description: "新NISAで積立すべき投資信託を信託報酬・運用実績・純資産額で比較。オルカン・S&P500・NASDAQ100・全米株式の違いと最適な配分を初心者向けに解説。",
    icon: "📊",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "insurance-comparison-2026",
    title: "【2026年】生命保険おすすめ比較｜会社員向け保障額と選び方",
    description: "生命保険・医療保険・がん保険・就業不能保険の必要性と選び方。公的保障を前提にした最小限の保険設計を家族構成別に解説。",
    icon: "🛡️",
    category: "household",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "tax-saving-salary-income",
    title: "【2026年】会社員ができる節税術10選｜年間30万円の手取りアップ",
    description: "iDeCo・新NISA・ふるさと納税・医療費控除・特定支出控除・副業経費計上まで。会社員でも年30万円以上の手取り増加を実現する合法節税術を網羅。",
    icon: "💡",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "mortgage-comparison-2026",
    title: "【2026年】住宅ローンおすすめ比較｜変動金利・固定金利・フラット35",
    description: "住信SBI・楽天銀行・auじぶん・PayPay・ソニー銀行・ARUHIの金利・団信・事務手数料を比較。変動0.3%台・フラット35・一括比較サービスの活用まで。",
    icon: "🏠",
    category: "household",
    readTime: "14分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "medical-insurance-comparison-2026",
    title: "【2026年】医療保険・がん保険おすすめ比較｜必要な保障額と選び方",
    description: "アフラック・オリックス・チューリッヒ・メディケア生命・県民共済の医療保険・がん保険を比較。公的医療保険との併用で月1,000円から最適な備えを構築。",
    icon: "🏥",
    category: "household",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "investing-50s-strategy",
    title: "【2026年】50代の資産運用戦略｜定年までの10年で1,500万円を作る",
    description: "50代からの新NISA・iDeCo・退職金運用の最適解。守りと攻めのバランス、60歳出口戦略、高配当株・債券・ロボアドの使い分けを解説。",
    icon: "🎯",
    category: "nisa",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "nisa-ideco-combined-strategy",
    title: "【2026年】新NISA×iDeCo 併用完全ガイド｜年齢別の優先順位と最強配分",
    description: "新NISAとiDeCoの違い・併用メリット・年代別優先順位を徹底解説。年収500万/800万/1,200万の3モデルで最適配分シミュレーション付き。",
    icon: "⚖️",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "housewife-investment-guide",
    title: "【2026年】主婦・主夫のための投資と副業ガイド｜103万・150万の壁と新NISA",
    description: "扶養内の主婦・主夫が知っておくべき新NISA・クレカ積立・在宅副業の始め方。103万/130万/150万円の壁を超えない範囲での収入アップ戦略。",
    icon: "👩",
    category: "sidejob",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "mortgage-refinance-guide",
    title: "【2026年】住宅ローン借り換え完全ガイド｜総返済額300万円減の実例",
    description: "変動0.3%台の今こそ借り換え好機。残高1,500万円以上・残期間10年以上・金利差1%以上なら総返済額で200〜500万円減。諸費用・団信切替・審査通過のコツを実例で解説。",
    icon: "♻️",
    category: "household",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "social-lending-comparison",
    title: "【2026年】ソーシャルレンディング比較｜Funds・SBI SL・クラウドバンク",
    description: "利回り4〜8%の貸付型クラウドファンディング主要5社を比較。Funds・SBIソーシャルレンディング・クラウドバンク・Crowd Realty・OwnersBookの案件タイプ・手数料・リスクを解説。",
    icon: "🏦",
    category: "fx-crypto",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "education-insurance-comparison",
    title: "【2026年】学資保険おすすめ比較｜ソニー生命・明治安田・日本生命",
    description: "返戻率105〜108%の学資保険主要5社を比較。新NISA成長投資枠との比較、払込期間・受取方法の選び方、子供の年齢別おすすめプランを解説。",
    icon: "🎓",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "tax-filing-software-comparison",
    title: "【2026年】確定申告ソフト比較｜freee・弥生・マネーフォワード",
    description: "副業・フリーランス向け確定申告ソフト3大サービスを料金・使いやすさ・機能で徹底比較。青色申告65万円控除を取るための最適な選び方を解説。",
    icon: "📝",
    category: "sidejob",
    readTime: "11分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "inheritance-planning-guide",
    title: "【2026年】相続対策・生前贈与完全ガイド｜年110万円非課税枠と相続時精算課税",
    description: "暦年贈与・相続時精算課税・教育資金一括贈与の3制度を徹底解説。2024年改正で生前贈与7年加算に強化。不動産・生命保険を活用した節税スキームまで。",
    icon: "🎁",
    category: "household",
    readTime: "14分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "retirement-2000-man-complete-guide",
    title: "【2026年】老後2000万円問題 完全対策ガイド｜世帯別必要額と準備シミュレーション",
    description: "老後2000万円問題は本当か？年金受給額・生活費・介護費用から逆算した必要資金を世帯別に試算。新NISA・iDeCo・退職金・個人年金を組み合わせた準備法。",
    icon: "👴",
    category: "nisa",
    readTime: "14分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "nisa-withdrawal-strategy",
    title: "【2026年】新NISA 出口戦略完全ガイド｜取り崩しの4%ルールと税務",
    description: "新NISAで築いた資産をいつ・どう取り崩すか。4%ルール・バケツ戦略・定率取崩の3手法を解説。65歳リタイア・70歳繰下げ年金との最適な組み合わせ。",
    icon: "🏁",
    category: "nisa",
    readTime: "12分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "takehome-maximize-by-income",
    title: "【2026年】年収別 手取り最大化戦略｜年収400/600/800/1000万円モデル",
    description: "iDeCo・ふるさと納税・新NISAを年収別にフル活用した手取り最大化シミュレーション。年収400万〜1,200万円の4パターンで具体的な節税額を試算。",
    icon: "💸",
    category: "household",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "bitcoin-long-term-strategy",
    title: "【2026年】ビットコイン長期保有戦略｜ドルコスト平均法と税務",
    description: "ビットコインを10年ガチホするならどう買うか。ドルコスト平均法・時間分散・半減期サイクル・取引所セキュリティ・税金対策を実践的に解説。",
    icon: "₿",
    category: "fx-crypto",
    readTime: "13分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "blog-side-income-roadmap",
    title: "【2026年】副業ブログ収益化完全ロードマップ｜月10万円への最短ルート",
    description: "ブログ副業で月10万円を達成するまでの12ヶ月ロードマップ。ジャンル選定・WordPress構築・SEO・ASP選び・記事設計の実践マニュアル。",
    icon: "✍️",
    category: "sidejob",
    readTime: "15分",
    publishedAt: "2026-04-18",
  },
  {
    slug: "business-card-comparison-2026",
    title: "【2026年】法人・個人事業主向けビジネスカードおすすめ比較10選",
    description: "個人事業主・中小企業経営者向けにビジネスカードを徹底比較。freeeカード・三井住友カードビジネス・楽天ビジネス・JCBビジネス等、年会費/還元率/限度額/付帯サービスで選ぶ。",
    icon: "🏢",
    category: "card",
    readTime: "13分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "fp-consultation-guide",
    title: "【2026年】FP無料相談おすすめ比較｜保険・資産運用・住宅ローンの無料アドバイス",
    description: "保険見直しラボ・マネプロ・ほけんのトータルプロフェッショナル等、FP無料相談サービスを徹底比較。相談の流れ・断り方・おすすめの活用法まで解説。",
    icon: "🧑‍💼",
    category: "household",
    readTime: "11分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "dual-income-household-guide",
    title: "【2026年】共働き夫婦の資産運用ロードマップ｜世帯年収別の最適プラン",
    description: "世帯年収700万〜1500万円の共働き夫婦向け、新NISA・iDeCo・クレカ積立・児童手当を組み合わせた最適資産運用戦略。夫婦別口座・家計の折半方法も解説。",
    icon: "👫",
    category: "nisa",
    readTime: "14分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "real-estate-crowdfunding-comparison-2026",
    title: "【2026年】不動産クラウドファンディング比較10社｜利回り・最低投資額・実績",
    description: "COZUCHI・CREAL・利回りくん・OwnersBook等の不動産クラファン10社を徹底比較。想定利回り4〜10%、1万円から始められる新しい投資法。元本保全性・運営会社の実績で選ぶ。",
    icon: "🏢",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "tax-accountant-consultation-guide",
    title: "【2026年】税理士無料相談おすすめ比較｜個人事業主・フリーランス向け",
    description: "税理士ドットコム・税理士紹介ネットワーク・freee税理士検索を比較。確定申告・インボイス対応・節税コンサルまで、個人事業主向けに最適な税理士の選び方。",
    icon: "👔",
    category: "sidejob",
    readTime: "11分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "high-income-tax-strategy",
    title: "【2026年】年収1000万円超の節税戦略｜実践的な手取り最大化マニュアル",
    description: "年収1000万〜2000万円の高所得者向け節税マニュアル。iDeCo/小規模共済/ふるさと納税/生命保険/不動産投資/医療費控除を組み合わせて年100万円超の節税を実現する方法。",
    icon: "💰",
    category: "household",
    readTime: "15分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "fixed-cost-reduction-guide",
    title: "【2026年】固定費削減完全マニュアル｜年30万円以上の節約術",
    description: "通信費・保険・サブスク・光熱費・住居費を見直して年30万円以上節約。格安SIM乗換・保険見直し・電力自由化活用で実現する具体的手順を解説。",
    icon: "✂️",
    category: "household",
    readTime: "14分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "early-career-investment-roadmap",
    title: "【2026年】20代新社会人の資産形成ロードマップ｜月3万円から始める10年プラン",
    description: "20代の新社会人向け、月3万円から始める資産形成の10年ロードマップ。新NISAつみたて投資枠の活用法・固定費最適化・副業でのブースト戦略まで。",
    icon: "🌱",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "auto-insurance-comparison-2026",
    title: "【2026年】自動車保険おすすめ比較10社｜ネット型 vs 代理店型で年3万円節約",
    description: "ソニー損保・SBI損保・チューリッヒ・アクサダイレクト等のダイレクト型自動車保険を徹底比較。等級・車種・年齢別の保険料シミュレーション、代理店型との違いを解説。",
    icon: "🚗",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "ifa-service-comparison",
    title: "【2026年】IFA（独立系FA）おすすめ比較｜富裕層向け資産運用パートナー",
    description: "IFA（Independent Financial Advisor）の選び方とおすすめ事務所を徹底比較。証券会社よりも中立的な資産運用アドバイス、1億円以上の運用に強いIFAとの出会い方。",
    icon: "💼",
    category: "nisa",
    readTime: "12分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "freelance-retirement-guide",
    title: "【2026年】フリーランス・個人事業主の年金完全ガイド｜iDeCo/付加年金/国民年金基金",
    description: "会社員の3分の1しかない国民年金（老齢基礎年金）を補完する、フリーランスの年金戦略。iDeCo月6.8万円・付加年金・国民年金基金・小規模企業共済を組合せて老後月25万円を実現する方法。",
    icon: "👴",
    category: "ideco",
    readTime: "13分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "inheritance-tax-filing-guide",
    title: "【2026年】相続税申告おすすめ税理士比較｜費用相場と節税事例",
    description: "相続税申告を依頼する税理士の選び方と費用相場を解説。税理士ドットコム・相続税の窓口・ベンチャーサポート相続税理士法人等を比較。申告期限10ヶ月までの準備スケジュール。",
    icon: "📋",
    category: "household",
    readTime: "13分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "company-incorporation-guide",
    title: "【2026年】法人設立・会社設立代行サービス比較｜合同会社vs株式会社",
    description: "freee会社設立・マネフォ会社設立・弥生の設立支援等を料金・機能で比較。合同会社と株式会社の違い、設立後の税務・社会保険・ビジネスカードまで一気通貫で解説。",
    icon: "🏛️",
    category: "sidejob",
    readTime: "14分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "retirement-payout-investment",
    title: "【2026年】退職金運用完全ガイド｜1,500万円を5年・10年で増やす投資戦略",
    description: "退職金1,500〜2,500万円を新NISA・定期預金・投資信託・外貨建て保険で最適配分。一括投資 vs 分散投資、IFA相談・リタイア世代のリスク管理まで完全解説。",
    icon: "🎁",
    category: "nisa",
    readTime: "14分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "senior-shukatsu-guide",
    title: "【2026年】シニア向け終活・相続準備完全ガイド｜お墓・葬儀・遺言書",
    description: "60代以降に必要な終活を徹底解説。エンディングノート作成・遺言書・相続税対策・お墓（霊園）・葬儀社比較まで。家族に迷惑をかけない計画的な終活の進め方。",
    icon: "🌸",
    category: "household",
    readTime: "13分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "professional-asset-management",
    title: "【2026年】医師・弁護士・士業向け高所得者資産運用完全ガイド",
    description: "年収2,000万円超の医師・弁護士・税理士・公認会計士など専門職向け。IFA経由のプライベートバンキング・小規模企業共済・不動産投資・海外資産運用・事業承継まで。",
    icon: "⚕️",
    category: "nisa",
    readTime: "15分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "ideco-by-age-guide",
    title: "【2026年】年代別iDeCo最適プラン｜20代/30代/40代/50代のベストポートフォリオ",
    description: "20代から50代まで年代別に最適なiDeCoのポートフォリオ・配分・金融機関を解説。リスク許容度・運用期間・受取方法を年代別にシミュレーションで公開。",
    icon: "🏦",
    category: "ideco",
    readTime: "13分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "life-insurance-case-studies",
    title: "【2026年】生命保険見直しケーススタディ10選｜月1万円以上節約した実例",
    description: "30代共働き/40代子育て/50代独身/60代リタイア等、家族構成別の生命保険見直し実例10件を解説。過剰な終身保険を掛け捨てに切替えるだけで年12〜24万円節約。",
    icon: "📖",
    category: "household",
    readTime: "14分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "singlemother-investment-guide",
    title: "【2026年】シングルマザーの資産形成ガイド｜児童扶養手当×新NISA×副業で老後1,500万円",
    description: "シングルマザー世帯向けの資産運用戦略。児童扶養手当・母子父子寡婦福祉資金・新NISA・iDeCo・扶養内副業を組み合わせて老後1,500万円を実現する20年プラン。",
    icon: "👩‍👦",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "foreign-currency-deposit-guide",
    title: "【2026年】外貨預金完全ガイド｜為替リスク対策とおすすめネット銀行比較",
    description: "住信SBIネット銀行・ソニー銀行・楽天銀行等の外貨預金を為替手数料・金利・利便性で比較。米ドル・豪ドル・ユーロの投資戦略と、新NISAでの外貨建て投資との使い分けを解説。",
    icon: "💵",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "pension-deferment-strategy",
    title: "【2026年】年金繰下げ受給の戦略｜65歳vs70歳vs75歳の損益分岐点",
    description: "公的年金を70歳まで繰下げると受給額1.42倍、75歳まで繰下げで1.84倍。しかし損益分岐点は12年後と長期。健康寿命・資産状況から最適な繰下げ年齢を判断する方法。",
    icon: "⏰",
    category: "ideco",
    readTime: "12分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "sixties-nisa-exit-strategy",
    title: "【2026年】60代以降の新NISA出口戦略｜取り崩しの最適順序と税務",
    description: "60〜70代のNISA資産の取り崩し順序・4%ルール・定率取崩・バケツ戦略を解説。公的年金・退職金・iDeCoとの優先順位、相続対策を加味した出口設計まで網羅。",
    icon: "🏁",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "portfolio-rebalancing-guide",
    title: "【2026年】ポートフォリオリバランス完全ガイド｜年1回で運用利回りを1%改善",
    description: "株式・債券・REITの資産配分が崩れたときのリバランス手法。年1回・年2回・5%ルール・バンド幅ルールの比較、税コスト最小化の実践テクニック。",
    icon: "⚖️",
    category: "nisa",
    readTime: "11分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "corporate-dc-matching-guide",
    title: "【2026年】企業型DC・マッチング拠出 完全活用ガイド｜転職時の移換も解説",
    description: "企業型確定拠出年金（企業型DC）のマッチング拠出上限・運用商品選び・転職時のiDeCoへの移換手続きを解説。企業型DC加入者のiDeCo併用ルール2022年改正にも対応。",
    icon: "🏢",
    category: "ideco",
    readTime: "12分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "crypto-staking-lending-guide",
    title: "【2026年】暗号資産ステーキング・レンディング比較｜bitbank・GMO・コインチェック",
    description: "仮想通貨を預けて利息を得るステーキング・レンディングの仕組みとリスク。bitFlyer・コインチェック・GMOコイン・bitbank等の利率・対応通貨・税金を徹底比較。",
    icon: "💎",
    category: "fx-crypto",
    readTime: "12分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "nft-investment-basics",
    title: "【2026年】NFT投資入門ガイド｜始め方・税金・日本の主要マーケット比較",
    description: "NFT投資の基礎から、OpenSea・楽天NFT・LINE NFT・Adam byGMO等の日本系マーケット比較まで。税金（雑所得・総合課税）・詐欺対策・購入手順を解説。",
    icon: "🎨",
    category: "fx-crypto",
    readTime: "11分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "high-interest-bank-account-2026",
    title: "【2026年】高金利ネット銀行おすすめ比較10選｜普通預金0.2%超",
    description: "SBI新生銀行・あおぞら銀行・住信SBIネット銀行・楽天銀行等のネット銀行を普通預金金利・定期金利・ATM手数料・振込手数料で徹底比較。普通預金年0.2〜0.4%の高金利口座を厳選。",
    icon: "🏦",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "auto-loan-comparison-2026",
    title: "【2026年】自動車ローン比較10選｜金利1%台から始める賢い車購入",
    description: "銀行自動車ローン（住信SBI/楽天/東京スター）vsディーラーローンを金利・審査スピード・保証料で徹底比較。年利1.5〜3.0%台の低金利ローン選定で総返済額を50万円以上節約。",
    icon: "🚗",
    category: "household",
    readTime: "11分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "carrier-credit-card-comparison",
    title: "【2026年】キャリア系クレカ比較｜ドコモdカード/au PAYカード/ソフトバンクカード/楽天カード",
    description: "携帯キャリア別のクレジットカードを還元率・スマホ料金割引・キャンペーン特典で比較。ドコモ光・auひかり・ソフトバンク光との組み合わせでさらにお得に。",
    icon: "💳",
    category: "card",
    readTime: "11分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "freelance-insurance-comprehensive",
    title: "【2026年】フリーランス向け保険完全ガイド｜労災特別加入・所得補償・賠償責任",
    description: "フリーランス特有の労災特別加入制度・所得補償保険・賠償責任保険を徹底解説。年収別の必要保障額とFREENANCE・フリーナンス等のフリーランス向け統合サービスを比較。",
    icon: "🛡️",
    category: "sidejob",
    readTime: "12分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "student-investment-guide",
    title: "【2026年】学生向け投資ガイド｜バイト代月3万円で始める新NISAロードマップ",
    description: "18歳から新NISA口座開設可能。バイト代月3万円を積立NISAで運用し、40年で約4,575万円を作る戦略。SBI証券・楽天証券の学生向けキャンペーンとつまずきポイントを解説。",
    icon: "🎓",
    category: "nisa",
    readTime: "11分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "card-loan-comparison-2026",
    title: "【2026年】カードローンおすすめ比較10選｜低金利・無利息期間・審査スピード",
    description: "プロミス・アコム・アイフル・SMBCモビット・レイクALSA等のカードローンを金利・無利息期間・審査スピード・借入限度額で比較。年利3〜18%の中から低金利商品を厳選。",
    icon: "💴",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "elderly-care-cost-guide",
    title: "【2026年】介護費用完全ガイド｜在宅介護vs施設入居の費用相場とお金の準備",
    description: "要介護1〜5の介護費用相場（在宅月5〜15万円/施設月15〜30万円）を解説。公的介護保険・親の年金・家族負担額の試算、民間介護保険・介護休業給付金の活用まで。",
    icon: "👴",
    category: "household",
    readTime: "13分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "funeral-cost-guide",
    title: "【2026年】葬儀費用完全ガイド｜家族葬・一般葬・直葬の相場と格安葬儀社比較",
    description: "家族葬（50〜150万円）/一般葬（150〜300万円）/直葬（10〜50万円）の費用相場と内訳を解説。いい葬儀・小さなお葬式・よりそう葬儀等の全国対応の格安葬儀社を比較。",
    icon: "🕊️",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "wedding-consulting-comparison",
    title: "【2026年】結婚相談所おすすめ比較10選｜成婚率・料金・会員数で選ぶ",
    description: "IBJメンバーズ・ゼクシィ縁結び・ツヴァイ・パートナーエージェント等の大手結婚相談所を成婚率・料金・会員数で比較。30代40代の結婚を本気で考える方向けの完全ガイド。",
    icon: "💍",
    category: "household",
    readTime: "13分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "tutoring-school-comparison",
    title: "【2026年】学習塾・家庭教師比較｜小中高生向けおすすめ10選",
    description: "東進・駿台・河合塾・トライ・家庭教師のノーバス等を料金・指導形式・合格実績で徹底比較。個別指導vs集団授業・オンライン塾の選び方、補助金活用法まで。",
    icon: "📚",
    category: "household",
    readTime: "13分",
    publishedAt: "2026-04-19",
  },
  {
    slug: "pet-insurance-comparison-2026",
    title: "【2026年】ペット保険おすすめ比較10選｜アイペット・アクサ・SBI日本興亜・PS保険",
    description: "犬・猫の医療費負担を軽減するペット保険10社を徹底比較。アイペット損保・アクサダイレクト・SBI日本興亜・PS保険・au損保等の補償内容・保険料・対応疾病で最適な1社を選ぶ。",
    icon: "🐾",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "online-english-school-comparison",
    title: "【2026年】オンライン英会話比較10選｜DMM英会話・ネイティブキャンプ・レアジョブ",
    description: "月額3,000〜1万円台のオンライン英会話を徹底比較。DMM英会話・ネイティブキャンプ・レアジョブ・Bizmates・QQ English等の料金・講師数・レッスン品質で最適な1社を選ぶ。",
    icon: "🗣️",
    category: "sidejob",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "programming-school-comparison-2026",
    title: "【2026年】プログラミングスクール比較｜エンジニア転職成功のおすすめ10選",
    description: "TechAcademy・DMM WEBCAMP・SAMURAI ENGINEER・tech boost等のプログラミングスクールを受講料・転職保証・学習期間で徹底比較。未経験からエンジニア転職を実現する方法。",
    icon: "💻",
    category: "sidejob",
    readTime: "14分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "finance-job-agent-comparison",
    title: "【2026年】金融系転職エージェントおすすめ比較｜年収800万円以上のハイクラス転職",
    description: "銀行・証券・保険・ファンドなど金融業界転職に強い転職エージェントを徹底比較。JACリクルートメント・ビズリーチ・リクルートエージェント・エンワールド等、年収UPを実現する選び方。",
    icon: "💼",
    category: "sidejob",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "marriage-app-comparison-2026",
    title: "【2026年】婚活マッチングアプリ比較｜Pairs・with・Omiai・ゼクシィ縁結び",
    description: "婚活・恋活マッチングアプリ主要10社を会員数・年齢層・料金・真剣度で徹底比較。30代40代の真剣婚活向けアプリ、結婚相談所との併用戦略まで解説。",
    icon: "💕",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "lawyer-consultation-comparison",
    title: "【2026年】弁護士無料相談サービス比較｜借金・離婚・相続・労働問題",
    description: "弁護士ドットコム・法テラス・ベリーベスト法律事務所・アディーレ等、無料相談可能な弁護士サービスを専門分野・費用体系・対応スピードで比較。",
    icon: "⚖️",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "reverse-mortgage-guide",
    title: "【2026年】リバースモーゲージ完全ガイド｜自宅担保で老後資金を確保",
    description: "持ち家シニアの老後資金調達策リバースモーゲージを解説。三井住友信託銀行・東京スター銀行・みずほ銀行・地方銀行の商品比較、メリット・デメリット・活用事例まで。",
    icon: "🏘️",
    category: "nisa",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "moving-cost-saving-guide",
    title: "【2026年】引越し費用節約完全ガイド｜一括見積もり比較で20万円安く",
    description: "SUUMO引越し・引越し侍・LIFULL引越し等の一括見積もりサービスと、サカイ引越センター・アート引越センター等の大手業者を比較。3〜8月の繁忙期と9〜2月の通常期で費用を50%圧縮する方法。",
    icon: "📦",
    category: "household",
    readTime: "11分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "home-renovation-loan-comparison",
    title: "【2026年】リフォームローン比較｜金利1%台の低金利商品と補助金活用",
    description: "住宅ローン型・カードローン型・無担保型のリフォームローンを金利・借入限度額・返済期間で比較。省エネリフォーム補助金・住宅ローン減税との組合せで総負担を最小化。",
    icon: "🔨",
    category: "household",
    readTime: "11分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "business-loan-comparison",
    title: "【2026年】事業者ローン・ビジネスローン比較10選｜即日融資・低金利・無担保",
    description: "日本政策金融公庫・銀行事業者ローン・ビジネクスト等のビジネスローンを金利・審査スピード・担保条件で比較。個人事業主・法人の運転資金・設備投資の調達方法を網羅。",
    icon: "💼",
    category: "sidejob",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "cashless-rewards-strategy",
    title: "【2026年】キャッシュレス還元最適化｜PayPay/楽天Pay/au PAY/d払いの使い分け",
    description: "PayPay・楽天Pay・au PAY・d払い・LINE Pay・メルペイの還元率・キャンペーン・経済圏連携を徹底比較。年間還元10万円超を狙う最適な使い分け戦略を解説。",
    icon: "📱",
    category: "card",
    readTime: "11分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "point-investment-complete-guide",
    title: "【2026年】ポイント投資完全ガイド｜楽天/Tポイント/Pontaで始める少額投資",
    description: "楽天ポイント・Tポイント・Pontaポイント・dポイントを使った投資方法を徹底解説。貯まったポイントで投資信託・株式購入、新NISAとの併用で実質無料の資産形成。",
    icon: "🎁",
    category: "nisa",
    readTime: "10分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "esg-investment-guide",
    title: "【2026年】ESG投資完全ガイド｜環境・社会・ガバナンスに配慮した銘柄選び",
    description: "ESG（Environment/Social/Governance）投資の基礎から、MSCI ESG指数連動ETF・グリーンボンド・SDGs関連投信まで。社会貢献と運用益を両立させる方法を解説。",
    icon: "🌱",
    category: "nisa",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "defi-beginners-guide",
    title: "【2026年】DeFi（分散型金融）日本語入門｜Uniswap/Aave/Compoundの始め方",
    description: "DeFi（分散型金融）の基礎から、Uniswap・Aave・Compound・Curve等の主要プロトコル、イールドファーミング・流動性提供のリスク・税金まで、日本人投資家向けに解説。",
    icon: "⛓️",
    category: "fx-crypto",
    readTime: "13分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "overseas-migration-tax-guide",
    title: "【2026年】海外移住の税金・年金完全ガイド｜非居住者の所得税・相続税対策",
    description: "海外移住者の日本での税務手続きを徹底解説。非居住者の所得税・住民税・相続税、出国税（1億円超）、国民年金・iDeCoの扱い、マレーシア/タイ/ポルトガル/ドバイ等の移住先別解説。",
    icon: "🌍",
    category: "household",
    readTime: "14分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "divorce-asset-division-guide",
    title: "【2026年】離婚時の財産分与完全ガイド｜夫婦の共有財産・慰謝料・年金分割",
    description: "離婚時の財産分与・慰謝料・養育費・年金分割を徹底解説。預貯金・不動産・退職金・iDeCo・新NISAの扱い、弁護士相談での交渉戦略まで。",
    icon: "💔",
    category: "household",
    readTime: "13分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "child-allowance-complete-guide",
    title: "【2026年】児童手当・子育て支援完全ガイド｜所得制限撤廃・第3子加算",
    description: "2024年10月改正で所得制限撤廃・高校生まで延長・第3子以降月3万円に拡充。児童手当の申請方法・受給額シミュレーション・新NISA積立活用法まで網羅。",
    icon: "👶",
    category: "household",
    readTime: "11分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "solar-energy-investment-guide",
    title: "【2026年】太陽光発電投資完全ガイド｜FIT制度・投資利回り・中古パネル市場",
    description: "太陽光発電投資の仕組みとFIT・FIP制度を解説。新築10kW以上の産業用、中古ソーラー、地方の遊休地活用、クラウドファンディング型太陽光投資まで比較。",
    icon: "☀️",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "mid-career-reskilling-guide",
    title: "【2026年】中高年のリスキリング完全ガイド｜40代50代から学ぶAI・IT・副業スキル",
    description: "40代50代からの学び直しに最適なスキル（プログラミング・AI・動画編集・Webマーケ・不動産投資等）と、助成金活用・教育訓練給付金で受講料実質負担を減らす方法。",
    icon: "🧠",
    category: "sidejob",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "premature-cleanup-guide",
    title: "【2026年】生前整理完全ガイド｜60代からの家財・デジタル遺品・相続準備",
    description: "60代以降に始める生前整理を徹底解説。家財整理・写真・貴重品・デジタル遺品（SNS/ネット銀行/暗号資産）・エンディングノート・遺言書まで、家族に迷惑をかけない準備法。",
    icon: "📦",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "gold-jewelry-buyback-comparison",
    title: "【2026年】金・宝石・貴金属買取おすすめ比較｜高価買取業者と相場変動",
    description: "バンバン・なんぼや・おたからや・おたからや等の金・宝石買取業者を徹底比較。金・プラチナの相場変動を読み、ダイヤモンド・ブランド時計も高価買取してもらうコツ。",
    icon: "💎",
    category: "household",
    readTime: "11分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "health-insurance-comparison-2026",
    title: "【2026年】医療保険おすすめ比較10選｜入院給付金・手術給付金・先進医療特約",
    description: "メットライフ生命・オリックス生命・アクサダイレクト生命・チューリッヒ生命等の医療保険を徹底比較。入院日額・手術給付金・先進医療特約・免責期間で最適な1社を選ぶ。",
    icon: "🏥",
    category: "household",
    readTime: "13分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "cancer-insurance-comparison-2026",
    title: "【2026年】ガン保険おすすめ比較10選｜診断一時金・通院特約・先進医療",
    description: "アクサダイレクト・チューリッヒ・メットライフ・オリックス生命等のガン保険を診断給付金・通院・先進医療で比較。上皮内新生物対応の違いまで解説。",
    icon: "🎗️",
    category: "household",
    readTime: "13分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "private-nursing-insurance-comparison",
    title: "【2026年】民間介護保険おすすめ比較｜公的介護保険との違いと必要性",
    description: "ソニー生命・メットライフ・SOMPO・東京海上日動等の民間介護保険を徹底比較。公的介護保険の不足分をカバーする仕組みと、必要な保障額の計算方法。",
    icon: "♿",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "income-protection-insurance-guide",
    title: "【2026年】所得補償保険おすすめ比較｜働けないときの収入保障",
    description: "アクサダイレクト・チューリッヒ・SBI損保・ライフネット生命等の所得補償保険・就業不能保険を徹底比較。月収の60〜80%を最大65歳まで保障する商品を厳選。",
    icon: "💼",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "travel-insurance-comparison",
    title: "【2026年】海外旅行保険おすすめ比較｜AIG・損保ジャパン・tabiho・t@bihoの違い",
    description: "AIG損保・損保ジャパン・エイチ・エス損保・東京海上日動等の海外旅行保険を徹底比較。治療・救援者費用・携行品損害・賠償責任の補償額と保険料のバランスで選ぶ。",
    icon: "✈️",
    category: "household",
    readTime: "11分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "bike-insurance-comparison",
    title: "【2026年】バイク保険おすすめ比較｜任意保険・自賠責・原付の選び方",
    description: "アクサダイレクト・チューリッヒ・三井ダイレクト・AIG損保等のバイク保険を徹底比較。任意保険の補償内容・等級・ロードサービス付帯で最適な1社を選ぶ。",
    icon: "🏍️",
    category: "household",
    readTime: "11分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "family-trust-guide",
    title: "【2026年】家族信託完全ガイド｜認知症対策・相続対策の新しい選択肢",
    description: "家族信託の仕組み・メリット・デメリットを徹底解説。成年後見制度との違い、不動産・預貯金の信託活用、司法書士・弁護士への依頼費用相場（30〜100万円）まで。",
    icon: "👨‍👩‍👧",
    category: "household",
    readTime: "13分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "severance-early-retirement-guide",
    title: "【2026年】早期退職金パッケージ活用戦略｜45歳以上の退職金加算・次のキャリア",
    description: "大手企業で増加中の早期退職・希望退職パッケージ（退職金＋割増金、通常の2〜3倍）の活用戦略。受給時の税務・次のキャリア設計・独立起業・早期リタイア等、45歳以上の選択肢を解説。",
    icon: "🚪",
    category: "sidejob",
    readTime: "13分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "credit-score-improve-guide",
    title: "【2026年】信用スコア改善ガイド｜住宅ローン・クレジットカード審査通過率UP",
    description: "個人信用情報（CIC/JICC/KSC）の確認方法と、信用スコアを改善する具体策。クレジットヒストリー・延滞記録の除去・借入過多の解消で、住宅ローン・プレミアムカード審査を通過させる方法。",
    icon: "📊",
    category: "card",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "angel-investment-japan-guide",
    title: "【2026年】エンジェル投資入門｜日本のエンジェル税制と成功するスタートアップ選び",
    description: "エンジェル投資（スタートアップへの個人投資）の仕組みと、日本独自の「エンジェル税制」で所得控除を受ける方法。FUNDINNO・イークラウド等の株式投資型クラファンも解説。",
    icon: "👼",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "year-end-tax-strategy",
    title: "【2026年】年末の節税総チェック｜12月までに実施すべき20項目",
    description: "年末までに行う節税対策を徹底解説。ふるさと納税・iDeCo最終積立・生命保険料控除・医療費控除・寄付金控除・小規模企業共済・住宅ローン控除の申請を網羅。",
    icon: "📅",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "corporate-tax-planning-guide",
    title: "【2026年】法人の節税戦略完全ガイド｜役員報酬・経費・減価償却を最適化",
    description: "法人の節税策を徹底網羅。役員報酬の最適配分・小規模企業共済・倒産防止共済・生命保険・減価償却・欠損金繰越控除・グループ通算制度まで、年収500万円〜3億円の法人向け戦略。",
    icon: "🏢",
    category: "sidejob",
    readTime: "14分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "sole-proprietor-tax-handbook",
    title: "【2026年】個人事業主のための税務完全マニュアル｜青色申告・経費・消費税対策",
    description: "個人事業主の税務を徹底解説。青色申告特別控除65万円の取り方、経費の上手な計上（家事按分・生命保険料・小規模企業共済等）、インボイス登録・消費税対応・確定申告の手順。",
    icon: "📗",
    category: "sidejob",
    readTime: "14分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "freelance-housing-loan-guide",
    title: "【2026年】フリーランス・個人事業主の住宅ローン攻略｜審査通過率と金融機関選び",
    description: "審査が厳しいと言われるフリーランスの住宅ローン。確定申告書3期分・所得要件・金融機関選び（フラット35/ソニー銀行/住信SBI等）で審査通過率を上げる実践的ノウハウを解説。",
    icon: "🏠",
    category: "sidejob",
    readTime: "13分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "japan-high-dividend-strategy",
    title: "【2026年】日本高配当株投資戦略｜年間配当60万円のポートフォリオ構築",
    description: "日本高配当株への長期投資で、配当金年60万円（月5万円）を実現するポートフォリオ構築法。三菱商事・伊藤忠・ソフトバンク・ENEOS・武田薬品等、高配当日本株の選び方と買付タイミング。",
    icon: "🗾",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "monthly-dividend-portfolio",
    title: "【2026年】毎月配当ポートフォリオ構築ガイド｜米国ETF・日本株で月10万円の不労所得",
    description: "毎月配当を受け取れるポートフォリオ構築法。米国高配当ETF（VYM/HDV/SPYD）・日本株・J-REIT・毎月分配型投信の組合せで、月10万円の配当収入を目指す実践戦略。",
    icon: "📅",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "online-store-setup-guide",
    title: "【2026年】ネットショップ開業完全ガイド｜BASE・STORES・Shopify・楽天市場比較",
    description: "ネットショップ開業の初心者向け完全ガイド。BASE・STORES・Shopify・楽天市場・Yahoo!ショッピングの手数料・機能を徹底比較。開業から売上10万円達成までのロードマップ。",
    icon: "🛒",
    category: "sidejob",
    readTime: "13分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "amazon-side-business-guide",
    title: "【2026年】Amazon物販副業完全ガイド｜せどり・OEM・FBA活用で月10万円",
    description: "Amazon物販（せどり・OEM・FBA）の始め方と月10万円達成のノウハウ。仕入れ先選び・利益計算・消費税の扱い・Amazon手数料の計算、初月から黒字化する実践テクニック。",
    icon: "📦",
    category: "sidejob",
    readTime: "13分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "childcare-leave-finance-guide",
    title: "【2026年】育休中の家計完全ガイド｜育休手当・社会保険料免除・生活費管理",
    description: "育休中の家計を守る完全ガイド。育児休業給付金（月給の67%→50%）・社会保険料免除・児童手当・生活費の見直し・復職後の準備まで、育休期間中の家計戦略。",
    icon: "👶",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "divorce-finance-recovery-guide",
    title: "【2026年】離婚後の家計再建ガイド｜シングル世帯の生活費・住居・資産形成",
    description: "離婚後の家計を再建する完全ガイド。シングル世帯の生活費節約・住居選び・児童扶養手当活用・養育費確保・新NISAでの資産形成・転職キャリア設計まで網羅。",
    icon: "🔄",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "second-home-investment-guide",
    title: "【2026年】2軒目不動産投資完全ガイド｜別荘・投資マンション・自宅オフィス",
    description: "2軒目の不動産購入戦略。別荘・投資用区分マンション・自宅オフィス・民泊物件等、目的別の物件選びとローン・税務の注意点。年収1,000万円超世帯向けの資産形成策。",
    icon: "🏘️",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "us-etf-core-satellite-strategy",
    title: "【2026年】米国ETF コア・サテライト戦略｜VTI/VOO＋テーマETFで長期リターン最大化",
    description: "米国ETF投資のコア（VTI/VOO/VT）＋サテライト（半導体SOXL・AIロボットROBO・クリーンエネルギーICLN等）の2層戦略。新NISAで20年運用時の期待リターンシミュレーション。",
    icon: "🌎",
    category: "nisa",
    readTime: "13分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "side-business-tax-accounting",
    title: "【2026年】副業の税務・会計完全ガイド｜20万円ルール・経費計上・確定申告",
    description: "会社員の副業に関する税務ルール。年20万円を超える副業所得の確定申告・雑所得vs事業所得・経費計上・住民税対策・副業バレ防止策まで完全解説。",
    icon: "💼",
    category: "sidejob",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "investment-trust-active-vs-index",
    title: "【2026年】アクティブ投信 vs インデックス投信｜20年でリターン差はどれくらい？",
    description: "アクティブ投信（ひふみ・さわかみ・セゾン等）vs インデックス投信（eMAXIS Slim・SBI・V・VT・楽天VT）の20年リターン比較。信託報酬の複利効果で数百万円の差を解説。",
    icon: "📊",
    category: "nisa",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "crowd-funding-donation-trust",
    title: "【2026年】寄付型クラウドファンディング完全ガイド｜ふるさと納税・NPO・認定NPO",
    description: "READYFOR・CAMPFIRE等の寄付型クラファン、ふるさと納税でのクラファン特集・NPO団体への寄付・認定NPO法人の税制優遇まで、社会貢献と節税を両立する方法を解説。",
    icon: "❤️",
    category: "household",
    readTime: "11分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "unemployment-benefits-guide",
    title: "【2026年】失業給付（雇用保険）完全ガイド｜自己都合・会社都合の受給期間と金額",
    description: "会社退職後の失業給付（雇用保険）を完全解説。自己都合退職（3ヶ月待機）vs 会社都合（即受給）の違い、受給期間90〜330日、月給与の50〜80%の支給額計算方法まで。",
    icon: "📄",
    category: "sidejob",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "maternity-leave-guide",
    title: "【2026年】産休・育休前の家計準備完全ガイド｜出産費用・貯蓄・保険見直し",
    description: "出産予定の家庭向け家計準備マニュアル。出産費用50〜80万円・出産育児一時金50万円・貯蓄の目安200〜300万円・保険見直し（加入・不要なものの解約）まで解説。",
    icon: "🤰",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
  {
    slug: "home-loan-refinancing-strategy",
    title: "【2026年】住宅ローン借換完全戦略｜金利差0.3%以上で総返済額100万円削減",
    description: "住宅ローン借換の判断基準（金利差0.3%以上＋残債1,000万円以上＋残期間10年以上）と、モゲチェック・住宅ローンnet等の一括比較サービス活用法。総返済額100〜500万円削減の実例。",
    icon: "🔄",
    category: "household",
    readTime: "12分",
    publishedAt: "2026-04-20",
  },
];

export function getGuideBySlug(slug: string) {
  return guides.find((g) => g.slug === slug);
}
